- name: Install core utils/services
  ansible.builtin.import_tasks: roles/core/tasks/core.yaml
  when: not ephemeral | bool

- name: Install common managers (flatpak, homebrew, nvm, pyenv, cargo and etc)
  ansible.builtin.import_tasks: roles/core/tasks/managers.yaml
