package_list:
  # Core
  - git
  - curl
  - pass
  - zsh
  - tmux
  - neovim
  # Utils cli/tui
  - eza
  - fd
  - fzf
  - bat
  - zoxide
  - ripgrep
  - btop
  # Tools
  - docker
  - docker-compose
  - zen
  #- ghostty
  #- vagrant
  - dbeaver

package_details:
  neovim:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  tmux:
    method: "{{ 'brew' if ansible_facts['distribution'] in ['Ubuntu'] else 'native' }}"
  eza:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  fd:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  fzf:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  bat:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  zoxide:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  ripgrep:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  btop:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  docker:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'skip' }}"
  docker-compose:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'skip' }}"
  zen:
    method: "flatpak"
    name: "app.zen_browser.zen"
  dbeaver:
    method: "flatpak"
    name: "io.dbeaver.DBeaverCommunity"
