- name: Install system-wide packages via official package manager
  ansible.builtin.import_tasks: roles/apps/tasks/pkgmanager.yaml

- name: Install packages for Archlinux
  ansible.builtin.import_tasks: roles/apps/tasks/arch.yaml
  when: ansible_distribution == 'Archlinux'

- name: Install packages for Ubuntu 24 LTS
  ansible.builtin.import_tasks: roles/apps/tasks/ubuntu.yaml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '24'

#- name: Install packages for Fedora 34
#  ansible.builtin.import_tasks: roles/apps/tasks/fedora.yaml
#  when: ansible_distribution == 'Fedora'

#- name: Install packages for openSUSE Tumbleweed
#  ansible.builtin.import tasks: roles/apps/tasks/opensuse.yaml
#  when: ansible_distribution == 'SUSE'

- name: Install sandboxed apps via flatpak
  ansible.builtin.import_tasks: roles/apps/tasks/flatpak.yaml
