- name: Install application launcher {{ applauncher }}
  ansible.builtin.package:
    name: "{{ desktop_applauncher }}"
    state: present

- name: Install Hyprland itself
  ansible.builtin.package:
    name: hyprland
    state: present

- name: Install taskbar {{ taskbar }}
  ansible.builtin.package:
    name: "{{ desktop_taskbar }}"
    state: present

- name: Install screen capture
  block:
    - name: Install screencapture util
      ansible.builtin.package:
        name: "{{ desktop_screencapture }}"
        state: present

    - name: Install screen location selecter (slurp)
      ansible.builtin.package:
        name: slurp
        state: present

- name: Install wallpaper setter {{ wallpaper }}
  ansible.builtin.package:
    name: "{{ desktop_wallpaper }}"
    state: present
