- name: Install Hyprland
  ansible.builtin.import_tasks: hyprland.yaml
  when: ansible_distribution == 'Archlinux'
#- name: Install GNOME
#  ansible.builtin.import_tasks: gnome.yaml
#  when: ansible_distribution == 'ArchLinux'
