desktop_applauncher: "wofi" # wofi (default)
desktop_wallpaper: "hyprpaper" # hyprpaper (default) | mpvpaper | swww
desktop_taskbar: "waybar" # waybar (default)
desktop_screencapture: "grim" # grim (default)
