package_list:
  # Core
  - git
  - curl
  - zsh
  - tmux
  - neovim
  # Utils cli/tui
  - eza
  - fd
  - fzf
  - bat
  - zoxide
  - repgrep
  - btop
  # Tools
  #- ghostty
  #- docker
  #- docker-compose
  #- vagrant
  #- dbeaver

package_details:
  neovim:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  tmux:
    method: "{{ 'brew' if ansible_facts['distribution'] in ['Ubuntu'] else 'native' }}"
  eza:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  fd:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  fzf:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  bat:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  zoxide:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  ripgrep:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
  btop:
    method: "{{ 'native' if ansible_facts['os_family'] in ['Archlinux'] else 'brew' }}"
